// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMMnNM8HmZnUE5D3AOsTpoPegRfC8sDfM',
    appId: '1:602564401198:web:7b68ab2abd44e855a4e7bf',
    messagingSenderId: '602564401198',
    projectId: 'flutter-quiz-c2315',
    authDomain: 'flutter-quiz-c2315.firebaseapp.com',
    databaseURL: 'https://flutter-quiz-c2315-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-c2315.firebasestorage.app',
    measurementId: 'G-4SN8CYQ33S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgb8NaPG49VBApkv2O_mR_n55s_Vj-iX8',
    appId: '1:602564401198:android:31e10aba90ecbf78a4e7bf',
    messagingSenderId: '602564401198',
    projectId: 'flutter-quiz-c2315',
    databaseURL: 'https://flutter-quiz-c2315-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-c2315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp8oSB9-c9ePsghIPec5vkMWmrnf4gTYU',
    appId: '1:602564401198:ios:ce40aed19a892695a4e7bf',
    messagingSenderId: '602564401198',
    projectId: 'flutter-quiz-c2315',
    databaseURL: 'https://flutter-quiz-c2315-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-quiz-c2315.firebasestorage.app',
    iosBundleId: 'com.ninezero.quiz',
  );
}
