name: setting
description: "setting package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.4.1
  event_bus: ^2.0.1